### ISSUE TITLE
CursorWindowAllocationException

### ISSUE THREAD

**Issue by MerlinYu** [pushtorefresh/storio#779] opened 2017-04-17 04:01 UTC
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at com.pushtorefresh.storio.sqlite.operations.put.DefaultPutResolver.performPut(SourceFile:74)
	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(SourceFile:112)
	at com.imaygou.android.data.MomosoDbManager.a(SourceFile:174)
	at com.imaygou.android.brand.BrandService.c(SourceFile:135)
	at com.imaygou.android.brand.BrandService.onHandleIntent(SourceFile:66)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:179)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nikitin-da** [comment] 2017-04-17 06:26
Duplicate of #778

**Closed by nikitin-da** 2017-04-17 06:26 UTC
