### ISSUE TITLE
Cannot resolve @StorIOSQLiteCreator

### ISSUE THREAD

**Issue by Saketme** [pushtorefresh/storio#727] opened 2016-12-06 12:36 UTC
Hello, I'm using the latest version of the library (1.11.0) and I cannot seem to be able to find `@StorIOSQLiteCreator`. I've these dependencies in my `build.gradle` file:

    compile 'com.pushtorefresh.storio:sqlite:1.11.0'
    compile 'com.pushtorefresh.storio:sqlite-annotations:1.11.0'
    apt 'com.pushtorefresh.storio:sqlite-annotations-processor:1.11.0'

Any idea what I'm missing?

**Comment by geralt-encore** [comment] 2016-12-06 12:54
Version with `@StorIOSQLiteCreator` hasn't been released yet. It should be available in 1.12 version. @artem-zinnatullin and @nikitin-da can say more about estimated release date.

**Comment by Saketme** [comment] 2016-12-06 12:55
Well, it's slightly confusing if you are adding unreleased features into your README :) 

Is it possible to use a snapshot version?

**Comment by geralt-encore** [comment] 2016-12-06 13:03
I understand you. It is particularly my fault since I have done PR with README update, but I didn't expect that it will be merged before the new version. Sorry for the confusion.
I think it should be possible to add current master snapshot using [jitpack](https://github.com/jitpack/jitpack.io).

**Comment by Saketme** [comment] 2016-12-06 13:09
A snapshot version will be really awesome. If that doesn't happen, we'll be forced to use something else :(

**Comment by artem-zinnatullin** [comment] 2016-12-06 16:08
We'll try to do release soon, don't worry :)

**Comment by nikitin-da** [comment] 2016-12-12 08:11
@Saketme check please 1.12.0!

**Comment by Saketme** [comment] 2016-12-16 11:10
@nikitin-da I'm seeing this error:

`Error:(37, 8) error: Please annotate class AutoValue_KiteNotification with StorIOSQLiteType`

**Comment by geralt-encore** [comment] 2016-12-16 11:12
@Saketme can you please show your class if it is possible?

**Comment by artem-zinnatullin** [comment] 2016-12-16 11:13
Daaamn. @geralt-encore looks like because of annotation processing rounds our annotation processor sees class generated by AutoValue, or I'm wrong

**Comment by Saketme** [comment] 2016-12-16 11:15
Sure, but can I email it to you instead?

**Comment by geralt-encore** [comment] 2016-12-16 11:33
@Saketme there is no more need I have been able to reproduce it.
@artem-zinnatullin the problem is, that `AutoValue` classes also inherit annotations from the original class methods. I think that the easiest solutions will be skipping classes which names start from `AutoValue_`.
I am deeply sorry because this is completely my fault and lack of proper testing. I was testing it using just regular abstract java classes assuming that it will be the same for `AutoValue` case.

**Comment by artem-zinnatullin** [comment] 2016-12-16 11:42
Nono, wait, no specific ignores, we need to find more general solution, I'm
pretty sure we can force it to inherit class level annotations too or
otherwise prevent it from inheriting any of our annotations!

**Comment by geralt-encore** [comment] 2016-12-16 12:16
Inherit class level annotation is not an option because then we will get two tables and that is not what we really need. After quick googling I haven't found anything related to annotations inheritance in AutoValue.

**Comment by artem-zinnatullin** [comment] 2016-12-16 12:26
I believe it's not AutoValue specific, I remember facing pretty similar
behavior but with Reflection lookup for child classes.

**Comment by geralt-encore** [comment] 2016-12-16 12:54
I think it has to be AutoValue specific because I remember that while working on others project annotation processor it didn't come up by default.

**Comment by artem-zinnatullin** [comment] 2016-12-16 13:37
Well, ok let's start with specific thing and then try to generalize it

**Comment by geralt-encore** [comment] 2016-12-16 17:26
@artem-zinnatullin so specific ignore then or you have a better idea?

**Comment by artem-zinnatullin** [comment] 2016-12-16 21:01
We can start with specific ignore. Or what about checking parent class
annotations and skip classes that have our annotations on parents?

**Comment by geralt-encore** [comment] 2016-12-16 21:30
I also was thinking about it but then I thought that if we want to introduce support for inheritance in future it might be a bad idea.

**Comment by artem-zinnatullin** [comment] 2016-12-16 21:50
Well, then child class will also need class level annotation and everything
will be ok!

**Comment by geralt-encore** [comment] 2017-01-03 08:28
@Saketme please verify that the issue is fixed in the latest version.

**Comment by Saketme** [comment] 2017-01-03 08:43
@geralt-encore I'm sorry, I didn't realize a fix has already been released. I will test the new version and report back.

**Comment by nikitin-da** [comment] 2017-08-27 10:18
Closing. Feel free to reopen if you met some problems

**Closed by nikitin-da** 2017-08-27 10:18 UTC
