### ISSUE TITLE
Auto generated GetResolver has constructor with wrong parameter order in Kotlin

### ISSUE THREAD

**Issue by pbochenski** [pushtorefresh/storio#735] opened 2016-12-12 11:05 UTC
Reproduction steps: 
1. create class with more than two columns f.e.
```kotlin
@StorIOSQLiteType(table = "CreditCard")
data class CreditCard @StorIOSQLiteCreator constructor(
        @get:StorIOSQLiteColumn(name = "id", key = true) val cardId: Long,
        @get:StorIOSQLiteColumn(name = "name") val name: String,
        @get:StorIOSQLiteColumn(name = "expireYear") val expireYear: Int,
        @get:StorIOSQLiteColumn(name = "expireMonth") val expireMonth: Int,
        @get:StorIOSQLiteColumn(name = "type") val type: String,
        @get:StorIOSQLiteColumn(name = "isDefault") val isDefault: Boolean)
```
2. build project (couple of times if needed). 

The reason for that is kapt (kotlins annotation processor, don't know about apt) does not process annotations in creation order.

**Comment by geralt-encore** [comment] 2016-12-12 11:16
Did you check it with kapt or kapt2?

**Comment by pbochenski** [comment] 2016-12-12 11:23
kapt1 I guess (I'm using '1.0.5-2' version of Kotlin)   
the one with 
```
kapt {
    generateStubs = true
}
```

**Comment by pbochenski** [comment] 2016-12-12 11:30
just checked with the new kapt (the one described here: https://blog.jetbrains.com/kotlin/2016/09/kotlin-1-0-4-is-here/) and the problem is still occurring.

**Comment by geralt-encore** [comment] 2016-12-12 12:11
Looks like I was very (un)fortunate with my Kotlin test case, but it's still my fault because I haven't tested it properly and was more concentrated on AutoValue case. I asked a question in Kotlin slack if it is expected behaviour or not. If it works as expected then I'll add an ordering parameter to column annotations and will sort fields according to it.
Thank you, very much for filing this issue! And sorry for inconvenience =(

**Comment by pbochenski** [comment] 2016-12-12 13:27
maybe some reflection can be used to avoid parameter numbering?

**Comment by geralt-encore** [comment] 2016-12-12 14:44
JetBrains guys said that kapt should behave in the same way as apt.
So here is an issue: https://youtrack.jetbrains.com/issue/KT-15202.
Since we don't know when it will be fixed and current version doesn't work I think we still need to do something even if the problem is on kapt side.

**Comment by geralt-encore** [comment] 2016-12-16 11:35
@artem-zinnatullin Kotlin support is broken atm. Shall we wait more answers and fixes from Kotlin team or shall we start acting upon it by ourselves?

**Comment by artem-zinnatullin** [comment] 2016-12-16 11:41
Do you think it's possible to give a fix from our side? Without reflection.

**Comment by pbochenski** [comment] 2016-12-16 11:45
I've just read some documentation, so I might be wrong but probably you can cast element annotated with ```@Creator``` annotation into ExecutableElement and it has ```getParameters()``` method. (see here: https://docs.oracle.com/javase/7/docs/api/javax/lang/model/element/ExecutableElement.html)

**Comment by geralt-encore** [comment] 2016-12-16 12:03
We can introduce new parameter order to `StorIOSqliteColumn` and sort parameters according to it before building parameters list

**Comment by artem-zinnatullin** [comment] 2016-12-16 12:25
That looks like too much manual work :(

**Comment by geralt-encore** [comment] 2016-12-16 17:25
@pbochenski you can't get variables name from there :(
@artem-zinnatullin not that much, but adding  more manual work for users is always bad, I agree.

**Comment by geralt-encore** [comment] 2016-12-17 11:50
I just checked that @pbochenski is actually right and you can get actual parameters names from `getParameters()` on `ExecutableElement`. So it should be possible to map columns with parameters relying just on their names.

**Comment by artem-zinnatullin** [comment] 2016-12-17 13:16
Nice!

**Comment by geralt-encore** [comment] 2017-01-03 08:29
@pbochenski please verify that the issue is fixed in the latest version.

**Comment by pbochenski** [comment] 2017-01-03 09:48
sorry but no. testing using this: https://github.com/pbochenski/kaptstoriobug 
the error is 
```
error: Problem occurred with StorIOProcessor: -1
e: /Users/bochen/Documents/kod/testy/kaptstoriobug/app/src/main/java/geraltencore/kaptstoriobug/CreditCardKotlin.kt: (1, 1): Some error(s) occurred while processing annotations. Please see the error messages above.
```

**Comment by geralt-encore** [comment] 2017-01-03 09:56
Sorry if I wasn't clear. I've changed implementation in StorIO for using parameters names instead of relying on fields order. So I was asking you to test this issue with version `1.12.1`. Kapt behaviour remains unchanged that's why test repo still doesn't work.

**Comment by pbochenski** [comment] 2017-01-03 10:24
@geralt-encore yes I know, I've forked your repo since it is nicely isolated problem and updated StorIO libraries as well as added kotlin-apt plugin.

**Comment by geralt-encore** [comment] 2017-01-03 12:14
That's a bummer 😔
 I tested it properly before making PR with the fix and it worked. Need to investigate it further...

**Closed** 2017-04-18 10:38 UTC
